# This file was generated by GoReleaser. DO NOT EDIT.
cask "darkubectl" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/darkubectl"], must_succeed: false
      end
    end
  end

  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "e0e184447a8abd91d301f63375b07c7063798f80a437713c2255314a4261e870"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e7bc6d62fb52f82fb5726f6e12e41b4256a400b907f87497a84b430779fe85b"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d0e0b90db893c98847aa7d42916d03fa00af168d7dc600dec1e54b7f018f909"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b575dd10a98ee08b4ccb1c58a180fca3f59424e5a4fff74906188276b4f8e97"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "darkubectl"
  desc "kubectl-like access to the Hamravesh Darkube platform"
  homepage "https://github.com/rahacloud/darkubectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "darkubectl"

  # No zap stanza required
end
