# This file was generated by GoReleaser. DO NOT EDIT.
cask "darkubectl" do
  postflight_steps do
    on_macos do
      if_path_exists "/usr/bin/xattr" do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/darkubectl"], must_succeed: false
      end
    end
  end

  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "ed4720398c46ffe680176aa03ac2091d8153866271ee0b0a398d8c3ff0bcd27a"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bda95b943c0432711754037fa44c041a7acbf5545f77258291e885390015c217"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b6f9fca73c7f38bfccad57303fc59fd48e8d6d68f314b31e3ec103c9bbad2481"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5b34dacbb88a235e3e019dc47af05e98ed9dcd8ee712bd71278a999de47a167c"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "darkubectl"
  desc "kubectl-like access to the Hamravesh Darkube platform"
  homepage "https://github.com/rahacloud/darkubectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "darkubectl"
  bash_completion "completions/darkubectl.bash"
  fish_completion "completions/darkubectl.fish"
  zsh_completion "completions/darkubectl.zsh"

  # No zap stanza required
end
