# This file was generated by GoReleaser. DO NOT EDIT.
cask "darkubectl" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "2f1b786fa07c590184339219eb36f99bfb99578b029c9be45bb0313224b39cb2"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "57701280e533536dbb390762dc9776ccadbc37068708582f628b9c56c81fb95d"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a7734f8a4a46abe2d24fa5aca31cadc97800c25c0f82e1b4fee0a1d85f1f3e0"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bae4c99866d0c1279d94c70d5cc68f01fae20d8b92b58d2e42eb3dc3544b75f"
      url "https://github.com/rahacloud/darkubectl/releases/download/v#{version}/darkubectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "darkubectl"
  desc "kubectl-like access to the Hamravesh Darkube platform"
  homepage "https://github.com/rahacloud/darkubectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "darkubectl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/darkubectl"]
    end
  end

  # No zap stanza required

end
